/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

/**
 *
 * @author Aleksandra
 */
public class MainForma extends javax.swing.JFrame {

    /**
     * Creates new form MainForma
     */
    public MainForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuIzborOpcije = new javax.swing.JMenu();
        jMenuItemIznajmljivanje = new javax.swing.JMenuItem();
        jMenuItemClanBiblioteke = new javax.swing.JMenuItem();
        jMenuItemBibliotekar = new javax.swing.JMenuItem();
        jMenuItemKnjiga = new javax.swing.JMenuItem();
        jMenuItemKategorijaOsobe = new javax.swing.JMenuItem();
        jMenuItemSmena = new javax.swing.JMenuItem();
        jMenuOAplikaciji = new javax.swing.JMenu();
        jMenuItemInformacije = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MISLI SLOBODNO");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("DOBRODOŠLI U BIBLIOTEKU \"MISLI SLOBODNO\"");

        jMenuIzborOpcije.setText("ODABIR OPCIJE");

        jMenuItemIznajmljivanje.setText("Iznajmljivanje");
        jMenuItemIznajmljivanje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIznajmljivanjeActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemIznajmljivanje);

        jMenuItemClanBiblioteke.setText("Član Biblioteke");
        jMenuItemClanBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClanBibliotekeActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemClanBiblioteke);

        jMenuItemBibliotekar.setText("Bibliotekar");
        jMenuItemBibliotekar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBibliotekarActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemBibliotekar);

        jMenuItemKnjiga.setText("Knjiga");
        jMenuItemKnjiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKnjigaActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemKnjiga);

        jMenuItemKategorijaOsobe.setText("Kategorija osobe");
        jMenuItemKategorijaOsobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKategorijaOsobeActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemKategorijaOsobe);

        jMenuItemSmena.setText("Smena");
        jMenuItemSmena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSmenaActionPerformed(evt);
            }
        });
        jMenuIzborOpcije.add(jMenuItemSmena);

        jMenuBar1.add(jMenuIzborOpcije);

        jMenuOAplikaciji.setText("O APLIKACIJI");

        jMenuItemInformacije.setText("Informacije");
        jMenuOAplikaciji.add(jMenuItemInformacije);

        jMenuBar1.add(jMenuOAplikaciji);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemIznajmljivanjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIznajmljivanjeActionPerformed
        new Iznajmljivanje().setVisible(true);
    }//GEN-LAST:event_jMenuItemIznajmljivanjeActionPerformed

    private void jMenuItemBibliotekarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBibliotekarActionPerformed
        new Bibliotekar().setVisible(true);
    }//GEN-LAST:event_jMenuItemBibliotekarActionPerformed

    private void jMenuItemSmenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSmenaActionPerformed
        new Smena().setVisible(true);
    }//GEN-LAST:event_jMenuItemSmenaActionPerformed

    private void jMenuItemClanBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClanBibliotekeActionPerformed
        new ClanBiblioteke().setVisible(true);
    }//GEN-LAST:event_jMenuItemClanBibliotekeActionPerformed

    private void jMenuItemKnjigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKnjigaActionPerformed
        new Knjiga().setVisible(true);
    }//GEN-LAST:event_jMenuItemKnjigaActionPerformed

    private void jMenuItemKategorijaOsobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKategorijaOsobeActionPerformed
        new KategorijaOsobe().setVisible(true);
    }//GEN-LAST:event_jMenuItemKategorijaOsobeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemBibliotekar;
    private javax.swing.JMenuItem jMenuItemClanBiblioteke;
    private javax.swing.JMenuItem jMenuItemInformacije;
    private javax.swing.JMenuItem jMenuItemIznajmljivanje;
    private javax.swing.JMenuItem jMenuItemKategorijaOsobe;
    private javax.swing.JMenuItem jMenuItemKnjiga;
    private javax.swing.JMenuItem jMenuItemSmena;
    private javax.swing.JMenu jMenuIzborOpcije;
    private javax.swing.JMenu jMenuOAplikaciji;
    // End of variables declaration//GEN-END:variables
}
