/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ClanBiblioteke;

/**
 *
 * @author Aleksandra
 */
public class ClanBibliotekeForma extends javax.swing.JFrame {

    Controller kontroler;
    ClanBiblioteke izabraniClan;
    List<ClanBiblioteke> pretrazeniClanovi;

    public List<ClanBiblioteke> getPretrazeniClanovi() {
        return pretrazeniClanovi;
    }

    public void setPretrazeniClanovi(List<ClanBiblioteke> pretrazeniClanovi) {
        this.pretrazeniClanovi = pretrazeniClanovi;
    }

    public void setIzabraniClan(ClanBiblioteke izabraniClan) {
        this.izabraniClan = izabraniClan;
    }

    public ClanBiblioteke getIzabraniClan() {
        return izabraniClan;
    }

    /**
     * Creates new form ClanBibliotekeForma
     */
    public ClanBibliotekeForma() {
        initComponents();
        kontroler = Controller.getinstance();
        pretrazeniClanovi = new ArrayList<>();
        ModelTabeleClanBiblioteke mtcb = new ModelTabeleClanBiblioteke(kontroler.ucitajClanoveIzBaze());
        jTableSviClanovi.setModel(mtcb);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jButtonObrisiClanBiblioteke = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonKreirajClanBiblioteke = new javax.swing.JButton();
        jButtonPretraziClanBiblioteke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSviClanovi = new javax.swing.JTable();
        jButtonPromeniClanBiblioteke = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonObrisiClanBiblioteke.setText("OBRIŠI");
        jButtonObrisiClanBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiClanBibliotekeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ČLAN BIBLIOTEKE");

        jButtonKreirajClanBiblioteke.setText("KREIRAJ");
        jButtonKreirajClanBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajClanBibliotekeActionPerformed(evt);
            }
        });

        jButtonPretraziClanBiblioteke.setText("PRETRAŽI");
        jButtonPretraziClanBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziClanBibliotekeActionPerformed(evt);
            }
        });

        jTableSviClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSviClanovi);

        jButtonPromeniClanBiblioteke.setText("PROMENI");
        jButtonPromeniClanBiblioteke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniClanBibliotekeActionPerformed(evt);
            }
        });

        jButton1.setText("OSVEŽI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonKreirajClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPretraziClanBiblioteke)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPromeniClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonObrisiClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPromeniClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonObrisiClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonKreirajClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPretraziClanBiblioteke, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajClanBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajClanBibliotekeActionPerformed
        KreirajClanBibliotekeForma kreiraj = new KreirajClanBibliotekeForma(this, true);
        kreiraj.setVisible(true);

    }//GEN-LAST:event_jButtonKreirajClanBibliotekeActionPerformed

    private void jButtonObrisiClanBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiClanBibliotekeActionPerformed
        int selektovaniRed = jTableSviClanovi.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Morate selektovati člana kog želite da obrišete");
        } else {
            int odgovor = JOptionPane.showConfirmDialog(this, "Da li ste sigurni?");
            if (odgovor == 0) {
                kontroler.obrisiClanaIzBaze(selektovaniRed);
                osveziTabelu();
            }
        }
    }//GEN-LAST:event_jButtonObrisiClanBibliotekeActionPerformed

    private void jButtonPromeniClanBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniClanBibliotekeActionPerformed
        int selektovaniRed = jTableSviClanovi.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite člana kog želite da promenite");
        } else {
            int id = kontroler.ucitajClanoveIzBaze().get(selektovaniRed).getId();
            String ime = kontroler.ucitajClanoveIzBaze().get(selektovaniRed).getIme();
            String prezime = kontroler.ucitajClanoveIzBaze().get(selektovaniRed).getPrezime();
            int cenaP = kontroler.ucitajClanoveIzBaze().get(selektovaniRed).getCenaPenala();
            int uk = kontroler.ucitajClanoveIzBaze().get(selektovaniRed).getUkupnoZaduzenje();
            ClanBiblioteke clan = new ClanBiblioteke(id, ime, prezime, cenaP, uk);
            izabraniClan = clan;
            PromeniClanBibliotekeForma pcbf = new PromeniClanBibliotekeForma(this, true);
            pcbf.setVisible(true);

//            jTextFieldCenaPenala.setText(cenaP + "");
//            jTextFieldIDClanaBiblioteke.setText(id + "");
//            jTextFieldImeClanaBiblioteke.setText(ime);
//            jTextFieldPrezimeClanaBiblioteke.setText(prezime);
//            jTextFieldUkupnoZaduzenje.setText(uk + "");
//            jTextFieldIDClanaBiblioteke.disable();
        }
    }//GEN-LAST:event_jButtonPromeniClanBibliotekeActionPerformed

    private void jButtonPretraziClanBibliotekeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziClanBibliotekeActionPerformed
        PretraziClanBibliotekeForma ptf = new PretraziClanBibliotekeForma(this, true);
        ptf.setVisible(true);
        ModelTabeleClanBiblioteke model = new ModelTabeleClanBiblioteke(pretrazeniClanovi);
        jTableSviClanovi.setModel(model);
        //PITAJ PROFESORA ZASTO MI NE PRIKAZUJE SVE CLANOVE (IMAM DVE SARE SAVIC)


    }//GEN-LAST:event_jButtonPretraziClanBibliotekeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ModelTabeleClanBiblioteke mtcb = new ModelTabeleClanBiblioteke(kontroler.ucitajClanoveIzBaze());
        jTableSviClanovi.setModel(mtcb);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClanBibliotekeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClanBibliotekeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClanBibliotekeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClanBibliotekeForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClanBibliotekeForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonKreirajClanBiblioteke;
    private javax.swing.JButton jButtonObrisiClanBiblioteke;
    private javax.swing.JButton jButtonPretraziClanBiblioteke;
    private javax.swing.JButton jButtonPromeniClanBiblioteke;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSviClanovi;
    // End of variables declaration//GEN-END:variables

    public void osveziTabelu() {
        ModelTabeleClanBiblioteke mtcb1 = new ModelTabeleClanBiblioteke(kontroler.ucitajClanoveIzBaze());
        jTableSviClanovi.setModel(mtcb1);
    }
}
